version: '3'

services:
  webapp:
    build: .
#    command: python -u run.py
    command: gunicorn --bind 0.0.0.0:5000 wsgi
    ports:
      - "5000:5000"
#    links:
#      - mongo
#    depends_on:
#      -mongo
#  mongo:
#    image: mongo
#    ports:
#      - "27017:27017"
